cedana-helm/templates/deployment.yaml, cedana-helm/templates/host-binary-daemon-service.yaml, cedana-helm/values.yaml
Pull policy can be fairly useful, and often we want to control it.
=> feat: allow customizable pull policy

cedana-helm/values.yaml
Set `values.yaml` to default update strategy.
=> fix: use k8s defaults for updateStrategy

.github/workflows/release.yml
=> feat: helm linting

cedana-helm/templates/manager-rbac.yaml
=> fix: add node list and watch verbs for new controller

cedana-helm/templates/_helpers.tpl, cedana-helm/templates/host-daemonset.yaml, cedana-helm/templates/manager-deployment.yaml, cedana-helm/templates/secrets.yaml, cedana-helm/templates/serviceaccount.yaml, cedana-helm/values.yaml
Adds changes from #17 and support for pre-existing secrets.
=> feat: support pre existing secrets

cedana-helm/templates/manager-deployment.yaml
=> fix: remove extra env defs

cedana-helm/templates/host-daemonset.yaml
=> fix: add --start-otelcol to args when starting daemonset

.github/workflows/pr.yml, .github/workflows/release.yml, cedana-helm/Chart.yaml
=> fix: release ci to use tags

.github/workflows/pr.yml
Testing env changes for the secrets, this is the reason deployment test is failing.
=> fix: add env for secret

cedana-helm/templates/manager-deployment.yaml
Fix manager values referencing daemonset
=> Fix manager values

.github/workflows/release.yml
=> fix: release ci chart path

examples/README.md, examples/redis-example.yaml, examples/redis-restore-example.yaml
Changes to facilitate a proper runc restore for redis
=> fix: a more descriptive readme for restore

cedana-helm/templates/host-daemonset-service.yaml, cedana-helm/templates/host-daemonset.yaml, cedana-helm/templates/manager-service.yaml
Manager service name & add it to daemon helper env
This is required by our daemon to be able to talk to the internal controller bidirectionally.
=> refactor: manager service name & add it to daemon helper env

cedana-helm/templates/manager-rbac.yaml
=> Fix: RBAC permissions for Kueue job creation

cedana-helm/templates/manager-deployment.yaml
=> fix: cedana-cluster-name env

cedana-helm/templates/manager-deployment.yaml, cedana-helm/templates/secrets.yaml, cedana-helm/values.yaml
=> Hotfix: Missing sqs env

cedana-helm/Chart.yaml
=> new release

cedana-helm/templates/configmap.yaml, cedana-helm/values.yaml
=> fix: revert change to gpu-shm-size

cedana-helm/templates/configmap.yaml, cedana-helm/values.yaml
Relates to https://github.com/cedana/cedana/pull/563/.
=> Add ld_paths to configmap and values.yaml. 

.github/pull_request_template.md, .github/runs-on.yml, .github/workflows/check.yml, .github/workflows/pr.yml, .github/workflows/publish.yml, .github/workflows/push.yml, .github/workflows/release.yml, cedana-helm/Chart.yaml, cedana-helm/templates/host-daemonset.yaml, cedana-helm/templates/manager-deployment.yaml, cedana-helm/templates/uninstaller-rbac.yaml, cedana-helm/templates/uninstaller.yaml, cedana-helm/values.yaml
Same as title. Additionally, bumps versions for next release and adds tests from https://github.com/cedana/cedana/pull/544.
=> CED-1338: Add digest to helm images + k3s tests

cedana-helm/templates/configmap.yaml, cedana-helm/templates/secrets.yaml
Made `config.clusterName`, `config.url`, `config.authToken` required values for the Helm chart to prevent uncaught errors in `helm install`.
=> CED-1420: Helm field validation on required values

cedana-helm/templates/configmap.yaml, cedana-helm/templates/host-daemonset.yaml, cedana-helm/templates/manager-deployment.yaml, cedana-helm/values.yaml
**Config rename: `clusterName` → `clusterId`**
- ConfigMap key: `cluster-name` → `cedana-cluster-id`
- Added `CEDANA_CLUSTER_ID` env var to host daemonset & manager deployment
- Updated values.yaml parameter
=> CED-1421: feat: cluster id over name
